### ISSUE TITLE
NameError: name 'from_scratch_results' is not defined

### ISSUE THREAD

**Issue by JackFurby** [mateoespinosa/concept-quality#1]
Receiving the following error after running the block following the heading "Dataset-wide Results" in the file `concept-quality/experiments/oracle_impurity_benchmark_tabular_toy.ipynb`. The undefined variable does not appear in any code blocks prior to this error.

```
NameError                                 Traceback (most recent call last)
Cell In[34], line 10
      4 real_values = np.array(list(map(lambda x: x*0.1, all_vars)))
      5 clrs = sns.color_palette("husl", 20)
      7 all_models = [
      8     (
      9         "Joint-CBM",
---> 10         from_scratch_results,
     11         "purity_scores",
     12         lambda x: normalize_purity(x, 3),
     13     ),
     14     (
     15         "CW MaxPool-Mean",
     16         cw_covariance_results,
     17         "purity_scores",
     18         lambda x: normalize_purity(x, 3),
     19     ),
     20     (
     21         "CW Feature Map",
     22         cw_covariance_results,
     23         "purity_scores",
     24         lambda x: normalize_purity(x, 3),
     25     ),
     26     (
     27         f"CCD (n\_concepts = {ccd_covariance_experiment_config['num_concepts']})",
     28         ccd_covariance_results,
     29         "purity_scores",
     30         lambda x: normalize_purity(x, 3),
     31     ),
     32     (
     33         f"CCD (n\_concepts = {ccd_covariance_double_experiment_config['num_concepts']})",
     34         ccd_covariance_double_results,
     35         "purity_scores",
     36         lambda x: normalize_purity(x, 3),
     37     ),
     38 ]
     40 num_models = len(all_models) + 1
     42 clrs = sns.color_palette("husl", num_models * 2)

NameError: name 'from_scratch_results' is not defined
```

**Comment by mateoespinosa** [comment]
Hi Jack!

Thanks so much for raising this issue. I am sorry for this typo, it happened as I ported everything from my research code into a slightly cleaner version ready for publication (and did the stupid and rushed decision of not testing every part of it). The code could still be orders of magnitude better/clearer, and it is on my TODO list to improve it once time allows. In the meantime, I have fixed this particular issue in this [commit](https://github.com/mateoespinosa/concept-quality/commit/c09d125aa4e057b8856561610d9fb571522b31a6). Please do raise additional tickets if you hit any other issues and let me know if this commit fixed the issue for you. Hope this helped!

Best of luck!
